### ISSUE TITLE
[BUG] Mod-package Editor - Saved mod with Indicative Category Custom causes unsaved changes

### ISSUE THREAD

**Issue by lmiol** [sedenion/OpenModMan#89] opened 2024-06-25 22:47 UTC
Preconditions: Mod already created in Local Library, mod saved with param Indicative Category Custom: MAP

1 right click on not installed mod on local library
2 click Open Mod-package Editor...
Actual Result: Save button is Active like i already did changes. If i try to close edit popup then shows up alert Unsaved changes and button Yes or No could works unproperly
Expected Result: Save button is inactive (because i did not changes)

the bug is not reproduced if the Indicative Category is not custom

**version of app is 1.2.7**

**Comment by sedenion** [comment] 2024-06-26 06:57
I am unable to reproduce this on my side, can you please provide link to a mod that produce this ?

**Comment by PraetorAugustus** [comment] 2024-06-26 18:12
> I am unable to reproduce this on my side, can you please provide link to a mod that produce this ?

I can confirm this behavior, but I haven't taken the time to test the specific circumstances. I'll start paying attention and hopefully one of us can give you more feedback and maybe how to reproduce it.

**Comment by lmiol** [comment] 2024-06-27 03:52
it seems problem of CUSTOM: TEXT + DESCRIPTION enabled + text

https://github.com/sedenion/OpenModMan/assets/264879/e2ba09cf-3f73-427e-99f4-cd4d7dc2a8ac

**Comment by PraetorAugustus** [comment] 2024-06-27 16:29
> it seems problem of CUSTOM: TEXT + DESCRIPTION enabled + text

Good catch, @lmiol .

@sedenion That matches my experience. Custom Category + Description = OMM asks to save even after I do a Save As.

It's a low-priority bug, though... annoying but not a game-breaker.

**Comment by sedenion** [comment] 2024-06-28 06:53
I think I found the problem. That is not specific to custom category or description but any changes, since the unsaved states of the several elements (category, desc, picture, etc. ) are not properly reset. This is fixed in source code.

**Closed by sedenion** 2024-06-28 06:53 UTC
